export enum AtbatType {
  None = 0,
  Unknown,
  BatterInterference,
  BuntGroundedIntoDoublePlay,
  BuntGroundout,
  BuntLineout,
  BuntPopout,
  BuntPopupIntoDoublePlay,
  CatcherInterference,
  Double,
  DoublePlay,
  FanInterference,
  FieldersChoice,
  FieldersChoiceOut,
  FieldError,
  FlyBallIntoDoublePlay,
  Flyout,
  Forceout,
  GroundedIntoDoublePlay,
  GroundedIntoTriplePlay,
  Groundout,
  GroundRuleDouble,
  HitByPitch,
  HomeRun,
  IntentionalWalk,
  LinedIntoDoublePlay,
  LinedIntoTriplePlay,
  Lineout,
  Popout,
  PoppedIntoDoublePlay,
  RunnerOut,
  SacrificeBunt,
  SacrificeBuntDoublePlay,
  SacrificeFly,
  SacrificeFlyDoublePlay,
  Single,
  Strikeout,
  StrikeoutDoublePlay,
  Triple,
  TriplePlay,
  Walk
}

export enum AtbatType2 {
  None = 0,
  Unknown,
  CaughtStealing2B,
  CaughtStealing3B,
  CaughtStealingHome,
  DefensiveIndifference,
  Error,
  PassedBall,
  PickedOffStealing2B,
  PickedOffStealing3B,
  PickedOffStealingHome,
  Pickoff1B,
  Pickoff2B,
  Pickoff3B,
  RunnerOut,
  StolenBase2B,
  StolenBase3B,
  StolenBaseHome,
  WildPitch
}

export enum LeftRight {
  Right,
  Left,
  Switch
}

export enum ActionType {
  None = 0,
  Unknown,
  Balk,
  BaseRunningDoublePlay,
  BatterTurn,
  CaughtStealing2B,
  CaughtStealing3B,
  CaughtStealingHome,
  DefensiveIndifference,
  DefensiveSubstitution,
  DefensiveSwitch,
  Ejection,
  Error,
  GameAdvisory,
  OffensiveSubstitution,
  PassedBall,
  PickedOffStealing2B,
  PickedOffStealing3B,
  PickedOffStealingHome,
  Pickoff1B,
  Pickoff2B,
  Pickoff3B,
  PickoffAttempt1B,
  PickoffAttempt2B,
  PickoffAttempt3B,
  PickoffError1B,
  PickoffError2B,
  PickoffError3B,
  PitchingSubstitution,
  PlayerInjured,
  RunnerAdvance,
  RunnerInterference,
  RunnerOut,
  StolenBase2B,
  StolenBase3B,
  StolenBaseHome,
  UmpireSubstitution,
  WildPitch
}

export enum ActionType2 {
  None = 0,
  Unknown,
  Error,
  CaughtStealing2B,
  CaughtStealing3B,
  CaughtStealingHome,
  PickedOffStealing2B,
  PickedOffStealing3B,
  PickedOffStealingHome
}
